networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0

compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"

reports:
  exclude_contracts:
    - SafeMath
